sudo: required
language: csharp
solution: src/SampleHelloWorldWeb.sln
services:
  - docker
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-1-003177
      mono: none
      env: DOTNETCORE=1
script:
  - chmod +x ./deploy-envs.sh
  - chmod +x ./Scripts/build.sh
  - chmod +x ./Scripts/deploy.sh
  - cd Scripts && ./build.sh
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ./deploy.sh; fi